blank_issues_enabled: true
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/vltpkg/statusboard/blob/main/README.md
    about: Check our documentation for guidance and information
