name: Add Issue/PR to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    # should only run when the PR is from the same repository
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Add to GitHub Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/vltpkg/projects/3
          github-token: ${{ secrets.PROJECT_PAT }}
